### ISSUE TITLE
I forked the repo and I am fixing the theme

### ISSUE THREAD

**Issue by slashformotion** [shawnohare/hugo-tufte#17]
Right now I fixed : 
- #14
- The shortcodes

MathJax have been replaced by Katex (because it's wayyyy faster. Benchmark [here](https://www.intmath.com/cg5/katex-mathjax-comparison.php?processor=MathJax3)). 

It is not production ready yet but it will be soon.

@shawnohare 

here is the link : https://github.com/slashformotion/hugo-tufte

**Comment by slashformotion** [comment]
#12 fixed

**Comment by slashformotion** [comment]
#9 fixed

**Comment by shawnohare** [comment]
Thanks for taking this up!

I will say that the choice of KaTeX should ideally be a configurable one. For example my own typesetting needs are not met by it, but I know it's more than suitable for many.

**Comment by slashformotion** [comment]
@shawnohare okay, i will implement that

**Comment by hieu6** [comment]
thank you both for your work on this lovely theme!

**Comment by hieu6** [comment]
> It is not production ready yet but it will be soon.

hi! if I am only interested in this theme for simple text blogging without katex latex codeblock other fanciness, would I be able to use your updated fork to get started?

what should i look out for to know when it's production ready? saw it on Hugo themes and got excited again

**Comment by slashformotion** [comment]
well you can turn off the latex support. And you can just decide to not use code blocks. I need to do a few tweaks before publishing the first release
