### ISSUE TITLE
Ready to demo?

### ISSUE THREAD

**Issue by sje30** [shawnohare/hugo-tufte#2]
hi,

Great idea to put a Tufte style into Hugo.  Have you got something that others can use yet? I'm interested to see how it might compare to other themes.  Best wishes, Stephen

**Comment by shawnohare** [comment]
@sje30 I apologize for the delay in response.  I somehow missed this issue.

The example site in the theme's `exampleSite` directory should provide a working example.  Extract the `exampleSite`, `cd` into it, and then:

```
mkdir themes
git clone https://shawnohare/hugo-tufte hugo-tufte
cd ..
hugo server
```

The theme should be relatively stable and aside from some blog-centric flourishes, looks almost identical to the Tufte-css example.  My plan was to use this for my own personal site with some further modifications made outside the theme proper.

**Comment by sje30** [comment]
thanks, this looks very neat.  Just got it working.

One thing: when I click on the "categories" tab, I see the two tables,
of entries by Frequency and alphabetically.  However, if I click on a
term, e.g. mathjax, I get sent to
http://localhost:1313/categories/categories/mathjax which makes a 404.

Stephen

**Comment by shawnohare** [comment]
Thanks for the report!

I actually cannot reproduce this locally with with Hugo v0.15 nor the latest dev build of Hugo, but I'll continue to poke around.  Meanwhile, I've opened a new issue.
