### ISSUE TITLE
Example Site categories tag link directs to a 404

### ISSUE THREAD

**Issue by shawnohare** [shawnohare/hugo-tufte#3]
From #2 as reported by @sje30

> One thing: when I click on the "categories" tab, I see the two tables,
> of entries by Frequency and alphabetically.  However, if I click on a
> term, e.g. mathjax, I get sent to
> http://localhost:1313/categories/categories/mathjax which makes a 404.

**Comment by sje30** [comment]
Thanks @shawnohare -- note the double "categories" in the path -- of course; removing one "categories" from the path makes the link work. 

This is with hugo 0.15 on mac/chrome.   Will dig further.

**Comment by sje30** [comment]
hi again, I've added my minimal example to http://sje30.github.io/categories/   (click on one of the tags to get the "404")

You can see the source files at https://github.com/sje30/sje30-tufte

**Comment by sje30** [comment]
great, thanks very much @shawnohare !
